/**
 * 10 realistic Alira Health xCSG engagements.
 * Each has Tier 1 (PMO) + Tier 2 (Expert) data.
 */

export interface Engagement {
  // Tier 1 — PMO fills
  projectName: string;
  category: string;          // must match category name in seed data
  client: string;
  pioneer: string;
  pioneerEmail: string;
  description: string;
  dateStarted: string;       // YYYY-MM-DD
  dateDelivered: string;
  xcsgDays: string;
  xcsgTeam: string;
  xcsgRevisions: string;
  scopeExpansion: string;
  // Optional legacy overrides (null = use category defaults)
  legacyDays?: string;
  legacyTeam?: string;
  legacyRevisions?: string;

  // Tier 2 — Expert fills
  expert: {
    b1: string;
    b2: string;
    b3: string;
    b4: string;
    c1: string;
    c2: string;
    c3: string;
    d1: string;
    d2: string;
    d3: string;
    f1: string;
    f2: string;
  };
}

export const engagements: Engagement[] = [
  {
    projectName: 'Solventum CDD Q1 2026',
    category: 'CDD',
    client: 'Solventum',
    pioneer: 'Bob Delise',
    pioneerEmail: 'bob.delise@alirahealth.com',
    description: 'Full commercial due diligence for advanced wound care portfolio acquisition.',
    dateStarted: '2026-01-15',
    dateDelivered: '2026-01-20',
    xcsgDays: '4-5',
    xcsgTeam: '1',
    xcsgRevisions: '0',
    scopeExpansion: 'Yes, expanded scope',
    expert: {
      b1: 'From AI draft',
      b2: '8-12',
      b3: '>75% AI',
      b4: 'Hypothesis-first (tested a specific thesis)',
      c1: 'Deep specialist in this TA/methodology',
      c2: 'Expert authored (with AI assist)',
      c3: '>75% judgment',
      d1: 'Yes',
      d2: 'Yes, directly reused and extended',
      d3: 'No \u2014 proprietary inputs decisive',
      f1: 'Not feasible \u2014 scope or timeline was only possible with AI',
      f2: 'Yes, with moderate customization',
    },
  },
  {
    projectName: 'Apposite Competitive Intel',
    category: 'Competitive Landscape',
    client: 'Apposite Capital',
    pioneer: 'Sarah Chen',
    pioneerEmail: 'sarah.chen@alirahealth.com',
    description: 'Competitive landscape for PE target in autoimmune space. 12 comparators analyzed.',
    dateStarted: '2026-01-22',
    dateDelivered: '2026-01-25',
    xcsgDays: '2-3',
    xcsgTeam: '1',
    xcsgRevisions: '1',
    scopeExpansion: 'No',
    expert: {
      b1: 'Mixed (AI structure, manual content)',
      b2: '4-7',
      b3: '50-75%',
      b4: 'Hybrid (hypothesis emerged during work)',
      c1: 'Adjacent expertise',
      c2: 'Expert co-authored (shared with team)',
      c3: '50-75%',
      d1: 'No',
      d2: 'Yes, provided useful starting context',
      d3: 'Partially \u2014 they would miss key insights',
      f1: 'Feasible but at 2x+ the cost and time',
      f2: 'Yes, with moderate customization',
    },
  },
  {
    projectName: 'J&J Market Access EU',
    category: 'Market Access',
    client: 'Johnson & Johnson',
    pioneer: 'Luis Korrodi',
    pioneerEmail: 'luis.korrodi@alirahealth.com',
    description: 'EU5 market access strategy for novel immunology biologic. HTA dossier prep + pricing.',
    dateStarted: '2026-02-01',
    dateDelivered: '2026-02-10',
    xcsgDays: '6-10',
    xcsgTeam: '2',
    xcsgRevisions: '1',
    scopeExpansion: 'Yes, new engagement',
    expert: {
      b1: 'From AI draft',
      b2: '13+',
      b3: '50-75%',
      b4: 'Hypothesis-first (tested a specific thesis)',
      c1: 'Deep specialist in this TA/methodology',
      c2: 'Expert authored (with AI assist)',
      c3: '>75% judgment',
      d1: 'Yes',
      d2: 'Yes, directly reused and extended',
      d3: 'No \u2014 proprietary inputs decisive',
      f1: 'Not feasible \u2014 scope or timeline was only possible with AI',
      f2: 'Yes, largely as-is',
    },
  },
  {
    projectName: 'BioHaven Investor Call Prep',
    category: 'Call Prep Brief',
    client: 'BioHaven',
    pioneer: 'Cameron Davidson',
    pioneerEmail: 'cameron.davidson@alirahealth.com',
    description: 'Quick-turn investor call brief on migraine pipeline competitive dynamics.',
    dateStarted: '2026-02-12',
    dateDelivered: '2026-02-12',
    xcsgDays: '1',
    xcsgTeam: '1',
    xcsgRevisions: '0',
    scopeExpansion: 'No',
    expert: {
      b1: 'From AI draft',
      b2: '4-7',
      b3: '>75% AI',
      b4: 'Hypothesis-first (tested a specific thesis)',
      c1: 'Generalist',
      c2: 'Expert reviewed only',
      c3: '25-50%',
      d1: 'No',
      d2: 'No, built from scratch',
      d3: 'Yes \u2014 all inputs publicly available',
      f1: 'Feasible at similar cost \u2014 xCSG provided marginal benefit',
      f2: 'No, fully bespoke',
    },
  },
  {
    projectName: 'Pfizer KOL Mapping Oncology',
    category: 'KOL Mapping',
    client: 'Pfizer',
    pioneer: 'Bob Delise',
    pioneerEmail: 'bob.delise@alirahealth.com',
    description: 'Global KOL identification and influence mapping for precision oncology CDx launch.',
    dateStarted: '2026-02-15',
    dateDelivered: '2026-02-25',
    xcsgDays: '6-10',
    xcsgTeam: '1',
    xcsgRevisions: '0',
    scopeExpansion: 'Yes, expanded scope',
    expert: {
      b1: 'From AI draft',
      b2: '13+',
      b3: '>75% AI',
      b4: 'Hypothesis-first (tested a specific thesis)',
      c1: 'Deep specialist in this TA/methodology',
      c2: 'Expert authored (with AI assist)',
      c3: '>75% judgment',
      d1: 'Yes',
      d2: 'Yes, directly reused and extended',
      d3: 'No \u2014 proprietary inputs decisive',
      f1: 'Not feasible \u2014 scope or timeline was only possible with AI',
      f2: 'Yes, largely as-is',
    },
  },
  {
    projectName: 'MediWound Financial Model',
    category: 'Financial Model',
    client: 'MediWound',
    pioneer: 'Sarah Chen',
    pioneerEmail: 'sarah.chen@alirahealth.com',
    description: 'Revenue forecast model for EscharEx wound care in US + EU markets.',
    dateStarted: '2026-03-01',
    dateDelivered: '2026-03-04',
    xcsgDays: '2-3',
    xcsgTeam: '1',
    xcsgRevisions: '1',
    scopeExpansion: 'No',
    expert: {
      b1: 'Mixed (AI structure, manual content)',
      b2: '4-7',
      b3: '25-50%',
      b4: 'Hybrid (hypothesis emerged during work)',
      c1: 'Adjacent expertise',
      c2: 'Expert co-authored (shared with team)',
      c3: '50-75%',
      d1: 'Yes',
      d2: 'Yes, provided useful starting context',
      d3: 'Partially \u2014 they would miss key insights',
      f1: 'Feasible but at 2x+ the cost and time',
      f2: 'Yes, with moderate customization',
    },
  },
  {
    projectName: 'Novartis Lupus Proposal',
    category: 'Proposal',
    client: 'Novartis',
    pioneer: 'Luis Korrodi',
    pioneerEmail: 'luis.korrodi@alirahealth.com',
    description: 'Unsolicited proposal for lupus registry data analysis and real-world evidence package.',
    dateStarted: '2026-03-05',
    dateDelivered: '2026-03-08',
    xcsgDays: '2-3',
    xcsgTeam: '1',
    xcsgRevisions: '0',
    scopeExpansion: 'Yes, new engagement',
    expert: {
      b1: 'From AI draft',
      b2: '8-12',
      b3: '>75% AI',
      b4: 'Hypothesis-first (tested a specific thesis)',
      c1: 'Deep specialist in this TA/methodology',
      c2: 'Expert authored (with AI assist)',
      c3: '>75% judgment',
      d1: 'Yes',
      d2: 'Yes, directly reused and extended',
      d3: 'No \u2014 proprietary inputs decisive',
      f1: 'Not feasible \u2014 scope or timeline was only possible with AI',
      f2: 'Yes, largely as-is',
    },
  },
  {
    projectName: 'Solventum Board Presentation Q2',
    category: 'Presentation',
    client: 'Solventum',
    pioneer: 'Cameron Davidson',
    pioneerEmail: 'cameron.davidson@alirahealth.com',
    description: 'Board-level strategic presentation on wound care market evolution and positioning.',
    dateStarted: '2026-03-10',
    dateDelivered: '2026-03-13',
    xcsgDays: '2-3',
    xcsgTeam: '2',
    xcsgRevisions: '1',
    scopeExpansion: 'Not yet delivered',
    expert: {
      b1: 'Mixed (AI structure, manual content)',
      b2: '1-3',
      b3: '25-50%',
      b4: 'Discovery-first (open-ended research)',
      c1: 'Adjacent expertise',
      c2: 'Expert co-authored (shared with team)',
      c3: '25-50%',
      d1: 'No',
      d2: 'No, built from scratch',
      d3: 'Yes \u2014 all inputs publicly available',
      f1: 'Feasible at similar cost \u2014 xCSG provided marginal benefit',
      f2: 'No, fully bespoke',
    },
  },
  {
    projectName: 'Roche CDD Rare Disease',
    category: 'CDD',
    client: 'Roche',
    pioneer: 'Bob Delise',
    pioneerEmail: 'bob.delise@alirahealth.com',
    description: 'Commercial due diligence for rare metabolic disease asset acquisition target.',
    dateStarted: '2026-03-15',
    dateDelivered: '2026-03-19',
    xcsgDays: '4-5',
    xcsgTeam: '1',
    xcsgRevisions: '0',
    scopeExpansion: 'Yes, expanded scope',
    expert: {
      b1: 'From AI draft',
      b2: '13+',
      b3: '>75% AI',
      b4: 'Hypothesis-first (tested a specific thesis)',
      c1: 'Deep specialist in this TA/methodology',
      c2: 'Expert authored (with AI assist)',
      c3: '>75% judgment',
      d1: 'Yes',
      d2: 'Yes, directly reused and extended',
      d3: 'No \u2014 proprietary inputs decisive',
      f1: 'Not feasible \u2014 scope or timeline was only possible with AI',
      f2: 'Yes, largely as-is',
    },
  },
  {
    projectName: 'AstraZeneca Competitive Landscape IO',
    category: 'Competitive Landscape',
    client: 'AstraZeneca',
    pioneer: 'Luis Korrodi',
    pioneerEmail: 'luis.korrodi@alirahealth.com',
    description: 'Immuno-oncology competitive landscape: 18 assets across 4 MOAs with clinical + commercial analysis.',
    dateStarted: '2026-03-20',
    dateDelivered: '2026-03-24',
    xcsgDays: '4-5',
    xcsgTeam: '2',
    xcsgRevisions: '0',
    scopeExpansion: 'Yes, new engagement',
    legacyDays: '20+',      // override: this was unusually complex
    legacyTeam: '4+',
    legacyRevisions: '3+',
    expert: {
      b1: 'From AI draft',
      b2: '13+',
      b3: '>75% AI',
      b4: 'Hypothesis-first (tested a specific thesis)',
      c1: 'Deep specialist in this TA/methodology',
      c2: 'Expert authored (with AI assist)',
      c3: '>75% judgment',
      d1: 'Yes',
      d2: 'Yes, directly reused and extended',
      d3: 'No \u2014 proprietary inputs decisive',
      f1: 'Not feasible \u2014 scope or timeline was only possible with AI',
      f2: 'Yes, largely as-is',
    },
  },
];
